[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "labrat"
dynamic = ["version"]
description = "A framework for running experiments in parallel."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
  { name = "Jeremy Silver", email = "jeremys@nessiness.com" }
]
classifiers = [
  "Programming Language :: Python"
]
dependencies = [
    "colorlog",
    "fancy_dataclass",
    "sqlalchemy",
    "toml",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
include = ["/labrat"]

[tool.hatch.version]
path = "labrat/__init__.py"

[tool.commitizen]
tag_format = "v$major.$minor.$patch"
