[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "labrat"
dynamic = ["version"]
description = "A framework for running computational experiments: hyperparameter sweeps, Monte Carlo, financial backtesting, and more."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [
  { name = "Jeremy Silver", email = "jeremys@nessiness.com" }
]
classifiers = [
  "Programming Language :: Python"
]
dependencies = [
  "colorlog",
  "fancy_dataclass >= 0.10.3",
  "sqlalchemy",
  "tqdm",
  "typing_extensions",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
include = ["/labrat"]

[tool.hatch.version]
path = "labrat/__init__.py"

[tool.hatch.envs.lint]
dependencies = [
  "mypy>=1.20",
  "ruff>=0.15",
  "types-tqdm",
  "vermin>=1.8",
]

[tool.hatch.envs.lint.scripts]
# linting
run-ruff = "ruff check {args:labrat tests}"
# ensure Python version compatibility
run-vermin = "vermin {args:.}"
# type-checking
run-mypy = "mypy --install-types --non-interactive {args:labrat tests}"
all = ["run-ruff", "run-vermin", "run-mypy"]

[tool.commitizen]
tag_format = "v$major.$minor.$patch"

[tool.mypy]
# exclude = ["tmp.*"]
warn_unused_configs = true
strict = true

# [[tool.mypy.overrides]]
# module = "tests.*"
# strict = false
# disable_error_code = ["arg-type", "attr-defined", "import-not-found", "index", "no-untyped-call", "no-untyped-def", "operator", "var-annotated"]
