target-version = "py310"
line-length = 120

[lint]

# rules to include

select = ["E", "F"]

extend-select = [
    "A",  # builtins
    "ANN",  # annotations
    "B",  # bugbear
    "C",  # mccabe (complexity)
    "C4",  # comprehensions
    "D",  # docstrings
    "I",  # isort (import order)
    "ICN",  # import conventions
    "PT",  # pytest style
    "PTH",  # pathlib
    "RET",  # return statements
    "RUF100",  # flag unused noqa
    "T10",  # debugger
    "UP",  # upgrades
]

# rules to ignore
# TODO: reactivate some of these
ignore = [
    "B905",  # zip without explicit 'strict' parameter
    "D100",  # module-level docstring
    "D101",  # public class docstring
    "D102",  # public method docstring
    "D104",  # public package docstring
    "D105",  # magic method docstring
    "D107",  # __init__ docstring
    "D203",  # blank line before class docstring
    "D204",  # blank line after class docstring
    "D205",  # blank line between summary and description
    "D209",  # newline before closing quotes
    "D213",  # multi-line summary start on second line
    "D401",  # docstrings in imperative mood
    "UP007",  # | instead of Union
    "UP045",  # | None instead of Optional
]

# paths to exclude
exclude = [
    ".venv",
    "tmp*"
]


# where to search for first-party imports
# src = ["src", "test"]

[lint.per-file-ignores]
"tests/*" = ["ANN", "D"]

[lint.flake8-pytest-style]
parametrize-names-type = "list"

[lint.isort]
# don't separate straight-style and 'from' imports for the same module
force-sort-within-sections = true
# force imports to the top of their section
force-to-top = ["package.utils"]
# patterns to separate into auxiliary blocks, in the order specified
# forced-separate = ["tests"]
# modules to consider first-party
# known-first-party = []
# number of lines after each import block?
lines-after-imports = 2
# whether to order imports by type, rather than strictly alphabetically
order-by-type = true
